apiVersion: v2
name: event-router
description: The VMware Event Router is used to connect to various VMware event providers and forwards received events to supported event processors.
home: https://vmweventbroker.io/
type: application
version: v0.8.0-pre-release
appVersion: release-v0.8.0
maintainers:
  - name: Michael Gasch
    email: mgasch@vmware.com
