toc:
  - title: Introduction
    subfolderitems:
      - page: Use Cases
        id: intro-about
        url: /kb/
      - page: Architecture
        id: intro-architecture
        url: /kb/architecture
      - page: VMware Tanzu Sources for Knative
        id: intro-tanzu-sources
        url: /kb/tanzu-sources
      - page: Functions
        id: intro-functions
        url: /kb/functions

  - title: Install
    subfolderitems:
      - page: VMware Event Broker Appliance
        id: install-veba
        url: /kb/install-veba

  - title: Use
    subfolderitems:
      - page: vCenter Events
        id: use-vcenter-events
        url: /kb/vcenter-events
      - page: Horizon Events
        id: use-horizon-events
        url: /kb/horizon-events
      - page: Event Specification
        id: use-eventspec
        url: /kb/eventspec
      - page: Deploy Functions
        id: use-functions
        url: /kb/use-functions

  - title: Contribute
    subfolderitems:
      - page: Getting Started
        id: contribute-start
        url: /kb/contribute-start
      - page: Build Functions
        id: contribute-functions
        url: /kb/contribute-functions
      - page: Build Appliance
        id: contribute-appliance
        url: /kb/contribute-appliance
      - page: Build Website
        id: contribute-site
        url: /kb/contribute-site

  - title: Advanced
    subfolderitems:
      - page: Deploy VEBA to Kubernetes
        id: advanced-deploy-k8s
        url: /kb/tanzu-sources#installation-tanzu-sources-for-knative
      - page: Deploy Tanzu Sources with KinD
        id: site-resources
        url: /kb/deploy-tanzu-sources-kind
      - page: Function Tutorial - Intro
        id: function-tutorial-intro
        url: /kb/function-tutorial-intro
      - page: Function Tutorial - Deploy
        id: function-tutorial-deploy
        url: kb/function-tutorial-deploy
      - page: Function Tutorial - Modify & Test
        id: function-tutorial-modtest
        url: /kb/function-tutorial-modtest
      - page: Certificate Management for VEBA
        id: advanced-certificates
        url: /kb/advanced-certificates
      - page: Using Private Container Registry with VEBA
        id: private-registry
        url: /kb/private-registry
      - page: Monitoring VEBA with Aria Operations
        id: site-resources
        external_url: https://docs.vmware.com/en/VMware-vRealize-Operations-Management-Pack-for-Kubernetes/1.8/management-pack-for-kubernetes/GUID-4ED07321-A5C9-46D6-8EB0-2661D853C0E9.html

  - title: Troubleshoot
    subfolderitems:
      - page: Troubleshooting Appliance
        id: troubleshoot-appliance
        url: /kb/troubleshoot-appliance
      - page: Troubleshooting Functions
        id: troubleshoot-functions
        url: /kb/troubleshoot-functions

  - title: More..
    subfolderitems:
      - page: FAQ
        id: site-faq
        url: /faq
      - page: Resources
        id: site-resources
        url: /resources
