name: Greeting

on:
  issues:
    types: ["opened"]

jobs:
  greeting:
    name: Send Greeting
    runs-on: ubuntu-latest
    # only send message to users not (yet) associated with repo
    # https://docs.github.com/en/graphql/reference/enums#commentauthorassociation
    if: github.event.issue.author_association == 'NONE'

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          fetch-depth: 1

      - name: Render template
        id: template
        uses: chuhlomin/render-template@a473db625a96c98e519d188812dc22bcaf54ffba
        with:
          template: .github/comment-template.md
          vars: |
            author: ${{ github.actor }}

      - name: Create comment
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043
        with:
          issue-number: ${{ github.event.issue.number }}
          body: ${{ steps.template.outputs.result }}
