name: Greeting

on:
  issues:
    types: ["opened"]

jobs:
  greeting:
    name: Send Greeting
    runs-on: ubuntu-latest
    # only send message to users not (yet) associated with repo
    # https://docs.github.com/en/graphql/reference/enums#commentauthorassociation
    if: github.event.issue.author_association == 'NONE'

    steps:
      - name: Checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
        with:
          fetch-depth: 1

      - name: Render template
        id: template
        uses: chuhlomin/render-template@204ce622bc2fd5c787ff5ca885ff19fb577e7a41
        with:
          template: .github/comment-template.md
          vars: |
            author: ${{ github.actor }}

      - name: Create comment
        uses: peter-evans/create-or-update-comment@67dcc547d311b736a8e6c5c236542148a47adc3d
        with:
          issue-number: ${{ github.event.issue.number }}
          body: ${{ steps.template.outputs.result }}
