name: VMware Event Router Linting

# triggered on every push and PRs but only when changes inside
# vmware-event-router (sub)dir(s)
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "vmware-event-router/**"
  push:
    paths:
      - "vmware-event-router/**"

jobs:
  golangci:
    name: lint
    strategy:
      matrix:
        go-version: ["1.19"]
        platform: ["ubuntu-latest"]

    runs-on: ${{ matrix.platform }}
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7
        with:
          go-version: ${{ matrix.go-version }}
          cache: false # use golangci-lint caching
        id: go

      - name: golangci-lint
        uses: golangci/golangci-lint-action@a4f60bb28d35aeee14e6880718e0c85ff1882e64
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: latest

          # Optional: working directory, useful for monorepos
          working-directory: vmware-event-router

          # Optional: golangci-lint command line arguments.
          args: --build-tags unit,integration -v --timeout 3m

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true
