name: VMware Event Router Linting

# triggered on every push and PRs but only when changes inside
# vmware-event-router (sub)dir(s)
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "vmware-event-router/**"
  push:
    paths:
      - "vmware-event-router/**"

jobs:
  golangci:
    name: lint
    strategy:
      matrix:
        go-version: ["1.18"]
        platform: ["ubuntu-latest"]

    runs-on: ${{ matrix.platform }}
    timeout-minutes: 20

    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@84cbf8094393cdc5fe1fe1671ff2647332956b1a
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: golangci-lint
        uses: golangci/golangci-lint-action@537aa1903e5d359d0b27dbc19ddd22c5087f3fbc
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: latest

          # Optional: working directory, useful for monorepos
          working-directory: vmware-event-router

          # Optional: golangci-lint command line arguments.
          args: --build-tags unit,integration -v --timeout 3m

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true
