name: Verify GCR Login

on:
  schedule:
    - cron: "5 1 * * *" # daily

  workflow_dispatch:

jobs:
  login:
    name: Verify GCR Login
    runs-on: ubuntu-latest
    timeout-minutes: 3
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

    steps:
      - name: Check out code
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f

      - id: login_to_gcp
        uses: google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@62d4898025f6041e16b1068643bfc5a696863587

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet
