name: Verify GCR Login

on:
  schedule:
    - cron: "5 1 * * *" # daily

  workflow_dispatch:

jobs:
  login:
    name: Verify GCR Login
    runs-on: ubuntu-latest
    timeout-minutes: 3
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

    steps:
      - name: Check out code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - id: login_to_gcp
        uses: google-github-actions/auth@35b0e87d162680511bf346c299f71c9c5c379033
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@e30db14379863a8c79331b04a9969f4c1e225e0b

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet
